name: "Set up Python and dependencies"
description: "Set up Python and dependencies"

inputs:
  python-version:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v4

    - name: Set up just
      uses: extractions/setup-just@v2

    - name: Install Tkinter on macOS
      if: runner.os == 'macOS'
      run: brew install python-tk@${{ matrix.python-version }}

    - name: Install dependencies and test
      run: |
        just prepare ".venv" "${{ matrix.python-version }}" "/opt/homebrew/bin"
