from .za import ZADevID, ZAItemID, ZAWaza

item_translation: dict[ZAItemID, str] = {
    "ITEMID_SAMEHADANAITO": "Sharpedonite",
    "ITEMID_OKKANOMI": "Occa Berry",
    "ITEMID_TOKENAIKOORI": "Never-Melt Ice",
    "ITEMID_ERUREIDONAITO": "Galladite",
    "ITEMID_PUTERANAITO": "Aerodactylite",
    "ITEMID_NOROINOOHUDA": "Spell Tag",
    "ITEMID_MIMIROPPUNAITO": "Lopunnite",
    "ITEMID_DOKUBARI": "Poison Barb",
    "ITEMID_SENSEINOTUME": "Quick Claw",
    "ITEMID_PIZYOTTONAITO": "Pidgeotite",
    "ITEMID_TYAAREMUNAITO": "Medichamite",
    "ITEMID_ZURUZUKINAITO": "Scraftynite",
    "ITEMID_ONIGOORINAITO": "Glalitite",
    "ITEMID_ENBUONAITO": "Emboarnite",
    "ITEMID_GOTUGOTUMETTO": "Rocky Helmet",
    "ITEMID_KAIGARANOSUZU": "Shell Bell",
    "ITEMID_RAIBORUTONAITO": "Manectite",
    "ITEMID_RYUUNOKIBA": "Dragon Fang",
    "ITEMID_METARUKOOTO": "Metal Coat",
    "ITEMID_ORENNOMI": "Oran Berry",
    "ITEMID_TABUNNENAITO": "Audinite",
    "ITEMID_TATUZINNOOBI": "Expert Belt",
    "ITEMID_MEGANIUMUNAITO": "Meganiumite",
    "ITEMID_OUZYANOSIRUSI": "King's Rock",
    "ITEMID_SURUDOIKUTIBASI": "Sharp Beak",
    "ITEMID_INOTINOTAMA": "Life Orb",
    "ITEMID_SIBIRUDONAITO": "Eelektrossite",
    "ITEMID_KATAIISI": "Hard Stone",
    "ITEMID_HASSAMUNAITO": "Scizorite",
    "ITEMID_HURAETTENAITO": "Floettite",
    "ITEMID_HERUGANAITO": "Houndoominite",
    "ITEMID_TAIREETUNAITO": "Falinknite",
    "ITEMID_TABENOKOSI": "Leftovers",
    "ITEMID_STAAMIINAITO": "Starmiite",
    "ITEMID_KAIROSUNAITO": "Pinsirite",
    "ITEMID_PIKUSINAITO": "Clefablite",
    "ITEMID_SINKANOKISEKI": "Eviolite",
    "ITEMID_NONE": "None",
    "ITEMID_OOKINANEKKO": "Big Root",
    "ITEMID_SYANDERANAITO": "Chandelurite",
    "ITEMID_YOUSEINOHANE": "Fairy Feather",
    "ITEMID_ITOKENOMI": "Yache Berry",
    "ITEMID_PENDORANAITO": "Scolipedite",
    "ITEMID_RIZAADONAITOx": "Charizardite X",
    "ITEMID_ZIZIIRONAITO": "Drampite",
    "ITEMID_EAAMUDONAITO": "Skarmoryite",
    "ITEMID_YAMIRAMINAITO": "Sablenite",
    "ITEMID_KAENZISINAITO": "Pyroarite",
    "ITEMID_BANGIRASUNAITO": "Tyranitarite",
    "ITEMID_DENKIDAMA": "Light Ball",
    "ITEMID_YUKINOONAITO": "Abomasite",
    "ITEMID_KARAMANERONAITO": "Malamarite",
    "ITEMID_SIRUKUNOSUKAAHU": "Silk Scarf",
    "ITEMID_GYARADOSUNAITO": "Gyaradosite",
    "ITEMID_DORAMIDORONAITO": "Dragalgite",
    "ITEMID_OODAIRUNAITO": "Feraligatrite",
    "ITEMID_MAGATTASUPUUN": "Twisted Spoon",
    "ITEMID_DORYUUZUNAITO": "Excadrite",
    "ITEMID_KISEKINOTANE": "Miracle Seed",
    "ITEMID_RINDONOMI": "Rindo Berry",
}
dev_translation: dict[ZADevID, str] = {
    "DEV_BUROSUTAA": "Flareon",
    "DEV_MAFOKUSII": "Delphox",
    "DEV_KAENZISI": "Pyroar",
    "DEV_HITOMOSI": "Litwick",
    "DEV_BAKUUDA": "Camerupt",
    "DEV_SUBOMII": "Budew",
    "DEV_SYAWAAZU": "Vaporeon",
    "DEV_ARIGEITU": "Croconaw",
    "DEV_PHI": "Leafeon",
    "DEV_GYARADOSU": "Gyarados",
    "DEV_FAIAROO": "Talonflame",
    "DEV_HIPOPOTASU": "Hippopotas",
    "DEV_DASUTODASU": "Garbodor",
    "DEV_PIZYOTTO": "Pidgeot",
    "DEV_GORONDA": "Pangoro",
    "DEV_HURAETTE": "Floette",
    "DEV_YANTYAMU": "Pancham",
    "DEV_ROZUREIDO": "Roserade",
    "DEV_KAIRIKII": "Machamp",
    "DEV_BANIRITTI": "Vanillish",
    "DEV_MHEEKURU": "Skiddo",
    "DEV_HAGANEERU": "Steelix",
    "DEV_SUTAAMII": "Starmie",
    "DEV_KUTIITO": "Mawile",
    "DEV_YADOKINGU": "Slowking",
    "DEV_SAMEHADAA": "Sharpedo",
    "DEV_NIDANGIRU": "Doublade",
    "DEV_NYASUPAA": "Espurr",
    "DEV_KARAMANERO": "Malamar",
    "DEV_KEROMATU": "Froakie",
    "DEV_EREZAADO": "Heliolisk",
    "DEV_AABOKKU": "Arbok",
    "DEV_AMARURUGA": "Aurorus",
    "DEV_FOKKO": "Fennekin",
    "DEV_YADORAN": "Slowbro",
    "DEV_MAAIIKA": "Inkay",
    "DEV_RARUTOSU": "Ralts",
    "DEV_SANAGIRASU": "Pupitar",
    "DEV_KAGEBOUZU": "Shuppet",
    "DEV_KIBANIA": "Carvanha",
    "DEV_NUMERUGON": "Goodra",
    "DEV_UTUBOTTO": "Weepinbell",
    "DEV_DERUBIRU": "Houndour",
    "DEV_HERUGAA": "Houndoom",
    "DEV_TIRUTARISU": "Altaria",
    "DEV_ABUSORU": "Absol",
    "DEV_HORUBII": "Bunnelby",
    "DEV_KAIRYUU": "Dragonite",
    "DEV_HOIIGA": "Whirlipede",
    "DEV_ONIGOORI": "Glalie",
    "DEV_IIBUI": "Eevee",
    "DEV_YUKIMENOKO": "Froslass",
    "DEV_RAKURAI": "Electrike",
    "DEV_ERUREIDO": "Gallade",
    "DEV_BAIBANIRA": "Vanilluxe",
    "DEV_HUKAMARU": "Gible",
    "DEV_HUREHUWAN": "Aromatisse",
    "DEV_BAOKKII": "Simisear",
    "DEV_DERIBAADO": "Delibird",
    "DEV_RIZAADON": "Charizard",
    "DEV_YADON": "Slowpoke",
    "DEV_KAIROSU": "Pinsir",
    "DEV_HITOTUKI": "Honedge",
    "DEV_ZURUGGU": "Scraggy",
    "DEV_METANGU": "Metang",
    "DEV_SIBISIRASU": "Tynamo",
    "DEV_RAIBORUTO": "Manectric",
    "DEV_HIYAKKII": "Simipour",
    "DEV_SAANAITO": "Gardevoir",
    "DEV_PEROPPAHU": "Swirlix",
    "DEV_MAGGYO": "Stunfisk",
    "DEV_ASANAN": "Meditite",
    "DEV_HAKURYUU": "Dragonair",
    "DEV_SANDAASU": "Jolteon",
    "DEV_HUSIGISOU": "Ivysaur",
    "DEV_KUREHFI": "Klefki",
    "DEV_EAAMUDO": "Skarmory",
    "DEV_YANAPPU": "Pansage",
    "DEV_PIPPI": "Clefairy",
    "DEV_ENBUOO": "Emboar",
    "DEV_PUTERA": "Aerodactyl",
    "DEV_KUREBEESU": "Avalugg",
    "DEV_PIZYON": "Pidgeotto",
    "DEV_HURAAJESU": "Florges",
    "DEV_YAMIRAMI": "Sableye",
    "DEV_BIIDORU": "Weedle",
    "DEV_SYANDERA": "Chandelure",
    "DEV_PIKUSII": "Clefable",
    "DEV_SUTORAIKU": "Scyther",
    "DEV_KAMEKKUSU": "Blastoise",
    "DEV_WANINOKO": "Totodile",
    "DEV_PANPUZIN": "Gourgeist",
    "DEV_KAMEERU": "Wartortle",
    "DEV_BAKETTYA": "Pumpkaboo",
    "DEV_HARIBOOGU": "Quilladin",
    "DEV_GIRUGARUDO": "Aegislash",
    "DEV_MINIRYUU": "Dratini",
    "DEV_TABUNNE": "Audino",
    "DEV_POPPO": "Pidgey",
    "DEV_GABAITO": "Gabite",
    "DEV_SIBIBIIRU": "Eelektrik",
    "DEV_MERIIPU": "Mareep",
    "DEV_IWAAKU": "Onix",
    "DEV_TEERUNAA": "Braixen",
    "DEV_MOKOKO": "Flaaffy",
    "DEV_NUMERA": "Goomy",
    "DEV_GEKOGASIRA": "Frogadier",
    "DEV_HERAKUROSU": "Heracross",
    "DEV_GOOSUTO": "Haunter",
    "DEV_RIORU": "Riolu",
    "DEV_BAOPPU": "Pansear",
    "DEV_HUUDHIN": "Alakazam",
    "DEV_GATIGORASU": "Tyrantrum",
    "DEV_HIYAPPU": "Panpour",
    "DEV_YABUKURON": "Trubbish",
    "DEV_AABO": "Ekans",
    "DEV_NYAONIKUSU": "Meowstic",
    "DEV_MEGUROKO": "Sandile",
    "DEV_HASSAMU": "Scizor",
    "DEV_KOIKINGU": "Magikarp",
    "DEV_KOKUUN": "Kakuna",
    "DEV_PIKATYUU": "Pikachu",
    "DEV_EEFI": "Espeon",
    "DEV_YAYAKOMA": "Fletchling",
    "DEV_HUSIGIBANA": "Venusaur",
    "DEV_NINFIA": "Sylveon",
    "DEV_RUTYABURU": "Hawlucha",
    "DEV_SISIKO": "Litleo",
    "DEV_KUZUMOO": "Skrelp",
    "DEV_DORYUUZU": "Excadrill",
    "DEV_ONBAAN": "Noivern",
    "DEV_KABARUDON": "Hippowdon",
    "DEV_HORUUDO": "Diggersby",
    "DEV_UDEPPOU": "Clauncher",
    "DEV_YOOGIRASU": "Larvitar",
    "DEV_RUKARIO": "Lucario",
    "DEV_HINOYAKOMA": "Fletchinder",
    "DEV_KOKODORA": "Aron",
    "DEV_PENDORAA": "Scolipede",
    "DEV_OODAIRU": "Feraligatr",
    "DEV_GUREISIA": "Glaceon",
    "DEV_METAGUROSU": "Metagross",
    "DEV_MIMIRORU": "Buneary",
    "DEV_RIZAADO": "Charmeleon",
    "DEV_GOOSU": "Gastly",
    "DEV_DENRYUU": "Ampharos",
    "DEV_BANIPUTTI": "Vanillite",
    "DEV_HURABEBE": "Flabébé",
    "DEV_ARIADOSU": "Ariados",
    "DEV_MERESII": "Carbink",
    "DEV_MINEZUMI": "Patrat",
    "DEV_TYAOBUU": "Pignite",
    "DEV_KATIKOORU": "Bergmite",
    "DEV_WARUBIARU": "Krookodile",
    "DEV_YUKIWARASI": "Snorunt",
    "DEV_OOROTTO": "Trevenant",
    "DEV_SUPIAA": "Beedrill",
    "DEV_DORAMIDORO": "Dragalge",
    "DEV_ROZERIA": "Roselia",
    "DEV_BURAKKII": "Umbreon",
    "DEV_YUNGERAA": "Kadabra",
    "DEV_KEESHI": "Abra",
    "DEV_GOOGOOTO": "Gogoat",
    "DEV_YUKIKABURI": "Snover",
    "DEV_TYAAREMU": "Medicham",
    "DEV_NULL": "None",
    "DEV_HARIMARON": "Chespin",
    "DEV_GARUURA": "Kangaskhan",
    "DEV_ZYUPETTA": "Banette",
    "DEV_GENGAA": "Gengar",
    "DEV_EMONGA": "Emolga",
    "DEV_ONBATTO": "Noibat",
    "DEV_BEIRIIHU": "Bayleef",
    "DEV_RAITYUU": "Raichu",
    "DEV_ZIZIIRON": "Drampa",
    "DEV_DEDENNE": "Dedenne",
    "DEV_SIBIRUDON": "Eelektross",
    "DEV_BOKUREE": "Phantump",
    "DEV_TIRUTTO": "Swablu",
    "DEV_MEGANIUMU": "Meganium",
    "DEV_BURIGARON": "Chesnaught",
    "DEV_ERIKITERU": "Helioptile",
    "DEV_UTUDON": "Victreebel",
    "DEV_GAMENODESU": "Barbaracle",
    "DEV_TORIMIAN": "Furfrou",
    "DEV_KAMETETE": "Binacle",
    "DEV_MOGURYUU": "Drilbur",
    "DEV_GABURIASU": "Garchomp",
    "DEV_GOORIKII": "Machoke",
    "DEV_DONMERU": "Numel",
    "DEV_TAIREETU": "Falinks",
    "DEV_RANPURAA": "Lampent",
    "DEV_BOOMANDA": "Salamence",
    "DEV_MIMIROPPU": "Lopunny",
    "DEV_MADATUBOMI": "Bellsprout",
    "DEV_WANRIKII": "Machop",
    "DEV_POKABU": "Tepig",
    "DEV_BANGIRASU": "Tyranitar",
    "DEV_TIKORIITA": "Chikorita",
    "DEV_HITODEMAN": "Staryu",
    "DEV_YANAKKII": "Simisage",
    "DEV_NUMEIRU": "Sliggoo",
    "DEV_PITYUU": "Pichu",
    "DEV_ITOMARU": "Spinarak",
    "DEV_BIBIYON": "Vivillon",
    "DEV_KOMORUU": "Shelgon",
    "DEV_PERORIIMU": "Slurpuff",
    "DEV_ZURUZUKIN": "Scrafty",
    "DEV_WARUBIRU": "Krokorok",
    "DEV_MIRUHOGGU": "Watchog",
    "DEV_YUKINOOO": "Abomasnow",
    "DEV_HUSIDE": "Venipede",
    "DEV_KODORA": "Lairon",
    "DEV_SYUSYUPU": "Spritzee",
    "DEV_BOSUGODORA": "Aggron",
    "DEV_GEKKOUGA": "Greninja",
}
waza_translation: dict[ZAWaza, str] = {
    "WAZA_NULL": "Null",
    "WAZA_TUBASADEUTU": "Wing Attack",
    "WAZA_SOORAABIIMU": "Solar Beam",
    "WAZA_GIGADOREIN": "Giga Drain",
    "WAZA_YOUSEINOKAZE": "Fairy Wind",
    "WAZA_DAIMONZI": "Fire Blast",
    "WAZA_NAKIGOE": "Growl",
    "WAZA_DASUTOSYUUTO": "Gunk Shot",
    "WAZA_MAZIKARUSYAIN": "Dazzling Gleam",
    "WAZA_RYUUSEIGUN": "Draco Meteor",
    "WAZA_IYANAOTO": "Screech",
    "WAZA_HURAINGUPURESU": "Flying Press",
    "WAZA_DORIRURAINAA": "Drill Run",
    "WAZA_SIZAAKUROSU": "X-Scissor",
    "WAZA_HIKARINOKABE": "Light Screen",
    "WAZA_ZIBAKU": "Self-Destruct",
    "WAZA_AKUNOHADOU": "Dark Pulse",
    "WAZA_RYUUNOIBUKI": "Dragon Breath",
    "WAZA_TYOUHATU": "Taunt",
    "WAZA_OOBAAHIITO": "Overheat",
    "WAZA_KAMINARINOKIBA": "Thunder Fang",
    "WAZA_NEPPUU": "Heat Wave",
    "WAZA_BUNMAWASU": "Brutal Swing",
    "WAZA_MATOWARITUKU": "Infestation",
    "WAZA_KOTTONGAADO": "Cotton Guard",
    "WAZA_KAWARAWARI": "Brick Break",
    "WAZA_SIPPOWOHURU": "Tail Whip",
    "WAZA_SUITORU": "Absorb",
    "WAZA_NAMINORI": "Surf",
    "WAZA_TOSSIN": "Take Down",
    "WAZA_MAKIBISI": "Spikes",
    "WAZA_KAMINARIPANTI": "Thunder Punch",
    "WAZA_ROKKUBURASUTO": "Rock Blast",
    "WAZA_MUSINOSAZAMEKI": "Bug Buzz",
    "WAZA_HURIIZUDORAI": "Freeze-Dry",
    "WAZA_SUPIIDOSUTAA": "Swift",
    "WAZA_TURUNOMUTI": "Vine Whip",
    "WAZA_SUTOONEZZI": "Stone Edge",
    "WAZA_TATUMAKI": "Twister",
    "WAZA_IWAOTOSI": "Rock Throw",
    "WAZA_KINGUSIIRUDO": "King's Shield",
    "WAZA_HEBIIBONBAA": "Heavy Slam",
    "WAZA_SIROIKIRI": "Mist",
    "WAZA_NEMURIGONA": "Sleep Powder",
    "WAZA_MAZIKARUHUREIMU": "Mystical Fire",
    "WAZA_KIRISAKU": "Slash",
    "WAZA_TONBOGAERI": "U-turn",
    "WAZA_ZISIN": "Earthquake",
    "WAZA_KYUUKETU": "Leech Life",
    "WAZA_KAENGURUMA": "Flame Wheel",
    "WAZA_DENZIHA": "Thunder Wave",
    "WAZA_NENRIKI": "Confusion",
    "WAZA_DORAGONDAIBU": "Dragon Rush",
    "WAZA_EREKINETTO": "Electroweb",
    "WAZA_HEDOROWHEEBU": "Sludge Wave",
    "WAZA_GIGAINPAKUTO": "Giga Impact",
    "WAZA_TUBAMEGAESI": "Aerial Ace",
    "WAZA_DORAGONKUROO": "Dragon Claw",
    "WAZA_IKARINOMAEBA": "Super Fang",
    "WAZA_MIGAWARI": "Substitute",
    "WAZA_HAGANENOTUBASA": "Steel Wing",
    "WAZA_SYADOOKUROO": "Shadow Claw",
    "WAZA_AIANHEDDO": "Iron Head",
    "WAZA_HIITOSUTANPU": "Heat Crash",
    "WAZA_PAWAAWHIPPU": "Power Whip",
    "WAZA_DENKOUSEKKA": "Quick Attack",
    "WAZA_KINZOKUON": "Metal Sound",
    "WAZA_UDDOHANMAA": "Wood Hammer",
    "WAZA_DOKUBISI": "Toxic Spikes",
    "WAZA_HUKITOBASI": "Whirlwind",
    "WAZA_KOORINOKIBA": "Ice Fang",
    "WAZA_RIHUREKUTAA": "Reflect",
    "WAZA_PARABORATYAAZI": "Parabolic Charge",
    "WAZA_HURUITATERU": "Work Up",
    "WAZA_SAIKOKINESISU": "Psychic",
    "WAZA_BAKUONPA": "Boomburst",
    "WAZA_YADORIGINOTANE": "Leech Seed",
    "WAZA_BOUHUU": "Hurricane",
    "WAZA_HAROWHIN": "Halloween",
    "WAZA_NOSIKAKARI": "Body Slam",
    "WAZA_RASUTAAKANON": "Flash Cannon",
    "WAZA_BARETTOPANTI": "Bullet Punch",
    "WAZA_USONAKI": "Fake Tears",
    "WAZA_DOWASURE": "Amnesia",
    "WAZA_SAIMINZYUTU": "Hypnosis",
    "WAZA_KOUSOKUIDOU": "Agility",
    "WAZA_KAGEUTI": "Shadow Sneak",
    "WAZA_HONOONOKIBA": "Fire Fang",
    "WAZA_KAIHUKUHUUZI": "Heal Bell",
    "WAZA_TURARAOTOSI": "Icicle Crash",
    "WAZA_HINOKO": "Ember",
    "WAZA_KAMINARI": "Thunder",
    "WAZA_HUNEN": "Lava Plume",
    "WAZA_DAITINOTIKARA": "Earth Power",
    "WAZA_TOKERU": "Acid Armor",
    "WAZA_INFAITO": "Close Combat",
    "WAZA_SAIKEKOUSEN": "Psybeam",
    "WAZA_KORAERU": "Endure",
    "WAZA_WAIDOBUREIKAA": "Superpower",
    "WAZA_BIRUDOAPPU": "Bulk Up",
    "WAZA_IWANADARE": "Rock Slide",
    "WAZA_PAWAAJEMU": "Power Gem",
    "WAZA_TOBIKAKARU": "Lunge",
    "WAZA_ZIKOSAISEI": "Recover",
    "WAZA_HAIPAABOISU": "Hyper Voice",
    "WAZA_GEKIRIN": "Outrage",
    "WAZA_KAMITUKU": "Bite",
    "WAZA_ZYUUDEN": "Charge",
    "WAZA_SUTERUSUROKKU": "Stealth Rock",
    "WAZA_SAIKOSYOKKU": "Psyshock",
    "WAZA_IWAKUDAKI": "Rock Smash",
    "WAZA_AKUAJETTO": "Aqua Jet",
    "WAZA_MIKIRI": "Detect",
    "WAZA_ASANOHIZASI": "Morning Sun",
    "WAZA_SAIKOKATTAA": "Psycho Cut",
    "WAZA_MEISOU": "Calm Mind",
    "WAZA_HONOONOUZU": "Fire Spin",
    "WAZA_TOBIHANERU": "Bounce",
    "WAZA_HAISUINOZIN": "No Retreat",
    "WAZA_GUROUPANTI": "Drain Punch",
    "WAZA_TUTUKU": "Peck",
    "WAZA_TAIATARI": "Tackle",
    "WAZA_HATAKIOTOSU": "Knock Off",
    "WAZA_ITOWOHAKU": "String Shot",
    "WAZA_HOUDEN": "Discharge",
    "WAZA_UDDOHOON": "Horn Leech",
    "WAZA_TURUGINOMAI": "Swords Dance",
    "WAZA_METARUKUROO": "Metal Claw",
    "WAZA_BABURUKOUSEN": "Bubble Beam",
    "WAZA_AMAERU": "Charm",
    "WAZA_ANAWOHORU": "Dig",
    "WAZA_ZINARASI": "Bulldoze",
    "WAZA_DAIBAKUHATU": "Explosion",
    "WAZA_SYADOOBOORU": "Shadow Ball",
    "WAZA_KOGOERUKAZE": "Icy Wind",
    "WAZA_GANSEKIHUUZI": "Rock Tomb",
    "WAZA_KOUGOUSEI": "Synthesis",
    "WAZA_MAMORU": "Protect",
    "WAZA_MAZIKARURIIHU": "Magical Leaf",
    "WAZA_RIIHUBUREEDO": "Leaf Blade",
    "WAZA_ZUTUKI": "Headbutt",
    "WAZA_SINENNOZUTUKI": "Zen Headbutt",
    "WAZA_TYAAMUBOISU": "Disarming Voice",
    "WAZA_KIAIDAMA": "Focus Blast",
    "WAZA_NEBANEBANETTO": "Sticky Web",
    "WAZA_HAIDOROPONPU": "Hydro Pump",
    "WAZA_NEGAIGOTO": "Wish",
    "WAZA_AIANTEERU": "Iron Tail",
    "WAZA_BORUTOTHENZI": "Volt Switch",
    "WAZA_SINPINOMAMORI": "Safeguard",
    "WAZA_SUTEMITAKKURU": "Double-Edge",
    "WAZA_HONOONOPANTI": "Fire Punch",
    "WAZA_HUREADORAIBU": "Flare Blitz",
    "WAZA_ENAZIIBOORU": "Energy Ball",
    "WAZA_KOROGARU": "Rollout",
    "WAZA_DOKUBARI": "Poison Sting",
    "WAZA_TUZIGIRI": "Night Slash",
    "WAZA_SIBIREGONA": "Stun Spore",
    "WAZA_HOERU": "Roar",
    "WAZA_HAMETUNOHIKARI": "Light of Ruin",
    "WAZA_RYUUNOHADOU": "Dragon Pulse",
    "WAZA_WAIRUDOBORUTO": "Wild Charge",
    "WAZA_DOREINKISSU": "Draining Kiss",
    "WAZA_SORAWOTOBU": "Fly",
    "WAZA_NIRAMITUKERU": "Leer",
    "WAZA_KATAKUNARU": "Harden",
    "WAZA_MEGAHOON": "Megahorn",
    "WAZA_MIRAIYOTI": "Future Sight",
    "WAZA_MADDOSYOTTO": "Mud Shot",
    "WAZA_HUBUKI": "Blizzard",
    "WAZA_NOROI": "Curse",
    "WAZA_MIZUNOHADOU": "Water Pulse",
    "WAZA_DENZIHOU": "Zap Cannon",
    "WAZA_DENKISYOKKU": "Thunder Shock",
    "WAZA_KAENHOUSYA": "Flamethrower",
    "WAZA_MUUNFOOSU": "Moonblast",
    "WAZA_HOPPESURISURI": "Nuzzle",
    "WAZA_10MANBORUTO": "Thunderbolt",
    "WAZA_AKUABUREIKU": "Liquidation",
    "WAZA_ONIBI": "Will-O-Wisp",
    "WAZA_REITOUPANTI": "Ice Punch",
    "WAZA_HEBINIRAMI": "Glare",
    "WAZA_MORINONOROI": "Forest's Curse",
    "WAZA_UZUSIO": "Whirlpool",
    "WAZA_MOROHANOZUTUKI": "Head Smash",
    "WAZA_HOROBINOUTA": "Perish Song",
    "WAZA_TEPPEKI": "Iron Defense",
    "WAZA_RIIHUSUTOOMU": "Leaf Storm",
    "WAZA_MAHHAPANTI": "Mach Punch",
    "WAZA_ENMAKU": "Smokescreen",
    "WAZA_KIAIDAME": "Focus Energy",
    "WAZA_KAMIKUDAKU": "Crunch",
    "WAZA_TUKINOHIKARI": "Moonlight",
    "WAZA_DOKUDOKU": "Toxic",
    "WAZA_FEZAADANSU": "Feather Dance",
    "WAZA_REITOUBIIMU": "Ice Beam",
    "WAZA_BAAKUAUTO": "Snarl",
    "WAZA_KAZEOKOSI": "Gust",
    "WAZA_AYASIIHIKARI": "Confuse Ray",
    "WAZA_EASURASSYU": "Air Slash",
    "WAZA_KAIDENPA": "Eerie Impulse",
    "WAZA_DOKUDUKI": "Poison Jab",
    "WAZA_SUNAZIGOKU": "Sand Tomb",
    "WAZA_TAKINOBORI": "Waterfall",
    "WAZA_SINSOKU": "Extreme Speed",
    "WAZA_TANEMASINGAN": "Bullet Seed",
    "WAZA_KOORINOTUBUTE": "Ice Shard",
    "WAZA_SUPAAKU": "Spark",
    "WAZA_HEDOROBAKUDAN": "Sludge Bomb",
    "WAZA_BUREIBUBAADO": "Brave Bird",
    "WAZA_YUBIWOHURU": "Metronome",
    "WAZA_HADOUDAN": "Aura Sphere",
    "WAZA_HAKAIKOUSEN": "Hyper Beam",
    "WAZA_DOKUNOKONA": "Poison Powder",
    "WAZA_GOOSUTODAIBU": "Phantom Force",
    "WAZA_MIZUDEPPOU": "Water Gun",
    "WAZA_AKUARINGU": "Aqua Ring",
    "WAZA_MISAIRUBARI": "Pin Missile",
    "WAZA_KAGEBUNSIN": "Double Team",
    "WAZA_BAKURETUPANTI": "Sky Uppercut",
    "WAZA_KONOHA": "Leafage",
    "WAZA_HAPPAKATTAA": "Razor Leaf",
    "WAZA_TEREPOOTO": "Teleport",
    "WAZA_ZYARETUKU": "Play Rough",
}
