from .za import ZAWaza

waza_translation: dict[ZAWaza, str] = {
    "WAZA_NULL": "Null",
    "WAZA_TUBASADEUTU": "Wing Attack",
    "WAZA_SOORAABIIMU": "Solar Beam",
    "WAZA_GIGADOREIN": "Giga Drain",
    "WAZA_YOUSEINOKAZE": "Fairy Wind",
    "WAZA_DAIMONZI": "Fire Blast",
    "WAZA_NAKIGOE": "Growl",
    "WAZA_DASUTOSYUUTO": "Gunk Shot",
    "WAZA_MAZIKARUSYAIN": "Dazzling Gleam",
    "WAZA_RYUUSEIGUN": "Draco Meteor",
    "WAZA_IYANAOTO": "Screech",
    "WAZA_HURAINGUPURESU": "Flying Press",
    "WAZA_DORIRURAINAA": "Drill Run",
    "WAZA_SIZAAKUROSU": "X-Scissor",
    "WAZA_HIKARINOKABE": "Light Screen",
    "WAZA_ZIBAKU": "Self-Destruct",
    "WAZA_AKUNOHADOU": "Dark Pulse",
    "WAZA_RYUUNOIBUKI": "Dragon Breath",
    "WAZA_TYOUHATU": "Taunt",
    "WAZA_OOBAAHIITO": "Overheat",
    "WAZA_KAMINARINOKIBA": "Thunder Fang",
    "WAZA_NEPPUU": "Heat Wave",
    "WAZA_BUNMAWASU": "Brutal Swing",
    "WAZA_MATOWARITUKU": "Infestation",
    "WAZA_KOTTONGAADO": "Cotton Guard",
    "WAZA_KAWARAWARI": "Brick Break",
    "WAZA_SIPPOWOHURU": "Tail Whip",
    "WAZA_SUITORU": "Absorb",
    "WAZA_NAMINORI": "Surf",
    "WAZA_TOSSIN": "Take Down",
    "WAZA_MAKIBISI": "Spikes",
    "WAZA_KAMINARIPANTI": "Thunder Punch",
    "WAZA_ROKKUBURASUTO": "Rock Blast",
    "WAZA_MUSINOSAZAMEKI": "Bug Buzz",
    "WAZA_HURIIZUDORAI": "Freeze-Dry",
    "WAZA_SUPIIDOSUTAA": "Swift",
    "WAZA_TURUNOMUTI": "Vine Whip",
    "WAZA_SUTOONEZZI": "Stone Edge",
    "WAZA_TATUMAKI": "Twister",
    "WAZA_IWAOTOSI": "Rock Throw",
    "WAZA_KINGUSIIRUDO": "King's Shield",
    "WAZA_HEBIIBONBAA": "Heavy Slam",
    "WAZA_SIROIKIRI": "Mist",
    "WAZA_NEMURIGONA": "Sleep Powder",
    "WAZA_MAZIKARUHUREIMU": "Mystical Fire",
    "WAZA_KIRISAKU": "Slash",
    "WAZA_TONBOGAERI": "U-turn",
    "WAZA_ZISIN": "Earthquake",
    "WAZA_KYUUKETU": "Leech Life",
    "WAZA_KAENGURUMA": "Flame Wheel",
    "WAZA_DENZIHA": "Thunder Wave",
    "WAZA_NENRIKI": "Confusion",
    "WAZA_DORAGONDAIBU": "Dragon Rush",
    "WAZA_EREKINETTO": "Electroweb",
    "WAZA_HEDOROWHEEBU": "Sludge Wave",
    "WAZA_GIGAINPAKUTO": "Giga Impact",
    "WAZA_TUBAMEGAESI": "Aerial Ace",
    "WAZA_DORAGONKUROO": "Dragon Claw",
    "WAZA_IKARINOMAEBA": "Super Fang",
    "WAZA_MIGAWARI": "Substitute",
    "WAZA_HAGANENOTUBASA": "Steel Wing",
    "WAZA_SYADOOKUROO": "Shadow Claw",
    "WAZA_AIANHEDDO": "Iron Head",
    "WAZA_HIITOSUTANPU": "Heat Crash",
    "WAZA_PAWAAWHIPPU": "Power Whip",
    "WAZA_DENKOUSEKKA": "Quick Attack",
    "WAZA_KINZOKUON": "Metal Sound",
    "WAZA_UDDOHANMAA": "Wood Hammer",
    "WAZA_DOKUBISI": "Toxic Spikes",
    "WAZA_HUKITOBASI": "Whirlwind",
    "WAZA_KOORINOKIBA": "Ice Fang",
    "WAZA_RIHUREKUTAA": "Reflect",
    "WAZA_PARABORATYAAZI": "Parabolic Charge",
    "WAZA_HURUITATERU": "Work Up",
    "WAZA_SAIKOKINESISU": "Psychic",
    "WAZA_BAKUONPA": "Boomburst",
    "WAZA_YADORIGINOTANE": "Leech Seed",
    "WAZA_BOUHUU": "Hurricane",
    "WAZA_HAROWHIN": "Halloween",
    "WAZA_NOSIKAKARI": "Body Slam",
    "WAZA_RASUTAAKANON": "Flash Cannon",
    "WAZA_BARETTOPANTI": "Bullet Punch",
    "WAZA_USONAKI": "Fake Tears",
    "WAZA_DOWASURE": "Amnesia",
    "WAZA_SAIMINZYUTU": "Hypnosis",
    "WAZA_KOUSOKUIDOU": "Agility",
    "WAZA_KAGEUTI": "Shadow Sneak",
    "WAZA_HONOONOKIBA": "Fire Fang",
    "WAZA_KAIHUKUHUUZI": "Heal Bell",
    "WAZA_TURARAOTOSI": "Icicle Crash",
    "WAZA_HINOKO": "Ember",
    "WAZA_KAMINARI": "Thunder",
    "WAZA_HUNEN": "Lava Plume",
    "WAZA_DAITINOTIKARA": "Earth Power",
    "WAZA_TOKERU": "Acid Armor",
    "WAZA_INFAITO": "Close Combat",
    "WAZA_SAIKEKOUSEN": "Psybeam",
    "WAZA_KORAERU": "Endure",
    "WAZA_WAIDOBUREIKAA": "Superpower",
    "WAZA_BIRUDOAPPU": "Bulk Up",
    "WAZA_IWANADARE": "Rock Slide",
    "WAZA_PAWAAJEMU": "Power Gem",
    "WAZA_TOBIKAKARU": "Lunge",
    "WAZA_ZIKOSAISEI": "Recover",
    "WAZA_HAIPAABOISU": "Hyper Voice",
    "WAZA_GEKIRIN": "Outrage",
    "WAZA_KAMITUKU": "Bite",
    "WAZA_ZYUUDEN": "Charge",
    "WAZA_SUTERUSUROKKU": "Stealth Rock",
    "WAZA_SAIKOSYOKKU": "Psyshock",
    "WAZA_IWAKUDAKI": "Rock Smash",
    "WAZA_AKUAJETTO": "Aqua Jet",
    "WAZA_MIKIRI": "Detect",
    "WAZA_ASANOHIZASI": "Morning Sun",
    "WAZA_SAIKOKATTAA": "Psycho Cut",
    "WAZA_MEISOU": "Calm Mind",
    "WAZA_HONOONOUZU": "Fire Spin",
    "WAZA_TOBIHANERU": "Bounce",
    "WAZA_HAISUINOZIN": "No Retreat",
    "WAZA_GUROUPANTI": "Drain Punch",
    "WAZA_TUTUKU": "Peck",
    "WAZA_TAIATARI": "Tackle",
    "WAZA_HATAKIOTOSU": "Knock Off",
    "WAZA_ITOWOHAKU": "String Shot",
    "WAZA_HOUDEN": "Discharge",
    "WAZA_UDDOHOON": "Horn Leech",
    "WAZA_TURUGINOMAI": "Swords Dance",
    "WAZA_METARUKUROO": "Metal Claw",
    "WAZA_BABURUKOUSEN": "Bubble Beam",
    "WAZA_AMAERU": "Charm",
    "WAZA_ANAWOHORU": "Dig",
    "WAZA_ZINARASI": "Bulldoze",
    "WAZA_DAIBAKUHATU": "Explosion",
    "WAZA_SYADOOBOORU": "Shadow Ball",
    "WAZA_KOGOERUKAZE": "Icy Wind",
    "WAZA_GANSEKIHUUZI": "Rock Tomb",
    "WAZA_KOUGOUSEI": "Synthesis",
    "WAZA_MAMORU": "Protect",
    "WAZA_MAZIKARURIIHU": "Magical Leaf",
    "WAZA_RIIHUBUREEDO": "Leaf Blade",
    "WAZA_ZUTUKI": "Headbutt",
    "WAZA_SINENNOZUTUKI": "Zen Headbutt",
    "WAZA_TYAAMUBOISU": "Disarming Voice",
    "WAZA_KIAIDAMA": "Focus Blast",
    "WAZA_NEBANEBANETTO": "Sticky Web",
    "WAZA_HAIDOROPONPU": "Hydro Pump",
    "WAZA_NEGAIGOTO": "Wish",
    "WAZA_AIANTEERU": "Iron Tail",
    "WAZA_BORUTOTHENZI": "Volt Switch",
    "WAZA_SINPINOMAMORI": "Safeguard",
    "WAZA_SUTEMITAKKURU": "Double-Edge",
    "WAZA_HONOONOPANTI": "Fire Punch",
    "WAZA_HUREADORAIBU": "Flare Blitz",
    "WAZA_ENAZIIBOORU": "Energy Ball",
    "WAZA_KOROGARU": "Rollout",
    "WAZA_DOKUBARI": "Poison Sting",
    "WAZA_TUZIGIRI": "Night Slash",
    "WAZA_SIBIREGONA": "Stun Spore",
    "WAZA_HOERU": "Roar",
    "WAZA_HAMETUNOHIKARI": "Light of Ruin",
    "WAZA_RYUUNOHADOU": "Dragon Pulse",
    "WAZA_WAIRUDOBORUTO": "Wild Charge",
    "WAZA_DOREINKISSU": "Draining Kiss",
    "WAZA_SORAWOTOBU": "Fly",
    "WAZA_NIRAMITUKERU": "Leer",
    "WAZA_KATAKUNARU": "Harden",
    "WAZA_MEGAHOON": "Megahorn",
    "WAZA_MIRAIYOTI": "Future Sight",
    "WAZA_MADDOSYOTTO": "Mud Shot",
    "WAZA_HUBUKI": "Blizzard",
    "WAZA_NOROI": "Curse",
    "WAZA_MIZUNOHADOU": "Water Pulse",
    "WAZA_DENZIHOU": "Zap Cannon",
    "WAZA_DENKISYOKKU": "Thunder Shock",
    "WAZA_KAENHOUSYA": "Flamethrower",
    "WAZA_MUUNFOOSU": "Moonblast",
    "WAZA_HOPPESURISURI": "Nuzzle",
    "WAZA_10MANBORUTO": "Thunderbolt",
    "WAZA_AKUABUREIKU": "Liquidation",
    "WAZA_ONIBI": "Will-O-Wisp",
    "WAZA_REITOUPANTI": "Ice Punch",
    "WAZA_HEBINIRAMI": "Glare",
    "WAZA_MORINONOROI": "Forest's Curse",
    "WAZA_UZUSIO": "Whirlpool",
    "WAZA_MOROHANOZUTUKI": "Head Smash",
    "WAZA_HOROBINOUTA": "Perish Song",
    "WAZA_TEPPEKI": "Iron Defense",
    "WAZA_RIIHUSUTOOMU": "Leaf Storm",
    "WAZA_MAHHAPANTI": "Mach Punch",
    "WAZA_ENMAKU": "Smokescreen",
    "WAZA_KIAIDAME": "Focus Energy",
    "WAZA_KAMIKUDAKU": "Crunch",
    "WAZA_TUKINOHIKARI": "Moonlight",
    "WAZA_DOKUDOKU": "Toxic",
    "WAZA_FEZAADANSU": "Feather Dance",
    "WAZA_REITOUBIIMU": "Ice Beam",
    "WAZA_BAAKUAUTO": "Snarl",
    "WAZA_KAZEOKOSI": "Gust",
    "WAZA_AYASIIHIKARI": "Confuse Ray",
    "WAZA_EASURASSYU": "Air Slash",
    "WAZA_KAIDENPA": "Eerie Impulse",
    "WAZA_DOKUDUKI": "Poison Jab",
    "WAZA_SUNAZIGOKU": "Sand Tomb",
    "WAZA_TAKINOBORI": "Waterfall",
    "WAZA_SINSOKU": "Extreme Speed",
    "WAZA_TANEMASINGAN": "Bullet Seed",
    "WAZA_KOORINOTUBUTE": "Ice Shard",
    "WAZA_SUPAAKU": "Spark",
    "WAZA_HEDOROBAKUDAN": "Sludge Bomb",
    "WAZA_BUREIBUBAADO": "Brave Bird",
    "WAZA_YUBIWOHURU": "Metronome",
    "WAZA_HADOUDAN": "Aura Sphere",
    "WAZA_HAKAIKOUSEN": "Hyper Beam",
    "WAZA_DOKUNOKONA": "Poison Powder",
    "WAZA_GOOSUTODAIBU": "Phantom Force",
    "WAZA_MIZUDEPPOU": "Water Gun",
    "WAZA_AKUARINGU": "Aqua Ring",
    "WAZA_MISAIRUBARI": "Pin Missile",
    "WAZA_KAGEBUNSIN": "Double Team",
    "WAZA_BAKURETUPANTI": "Sky Uppercut",
    "WAZA_KONOHA": "Leafage",
    "WAZA_HAPPAKATTAA": "Razor Leaf",
    "WAZA_TEREPOOTO": "Teleport",
    "WAZA_ZYARETUKU": "Play Rough",
}
