# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Personal import Personal
from typing import Optional
np = import_numpy()

class PersonalTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PersonalTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPersonalTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PersonalTable
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PersonalTable
    def Entry(self, j: int) -> Optional[Personal]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Personal()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PersonalTable
    def EntryLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PersonalTable
    def EntryIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PersonalTableStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    PersonalTableStart(builder)

def PersonalTableAddEntry(builder: flatbuffers.Builder, entry: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entry), 0)

def AddEntry(builder: flatbuffers.Builder, entry: int):
    PersonalTableAddEntry(builder, entry)

def PersonalTableStartEntryVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEntryVector(builder, numElems: int) -> int:
    return PersonalTableStartEntryVector(builder, numElems)

def PersonalTableEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PersonalTableEnd(builder)
