from .kanto_starters import *
from .kanto import *
from .johto import *
from .hoenn import *
from .sinnoh import *
from .hisui import *
from .unova import *
from .kalos import *
from .alola import *
from .galar import *
from .paldea import *
from .paradox import *
from .gods import *
