POKEMON = (
    "Egg",
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Mega Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Mega Charizard X",
    "Mega Charizard Y",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Mega Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Mega Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Mega Pidgeot",
    "Rattata",
    "Alolan Rattata",
    "Raticate",
    "Alolan Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Pikachu-1",
    "Pikachu-2",
    "Pikachu-3",
    "Pikachu-4",
    "Pikachu-5",
    "Pikachu-6",
    "Pikachu-7",
    "Pikachu-8",
    "Pikachu-9",
    "Raichu",
    "Alolan Raichu",
    "Sandshrew",
    "Alolan Sandshrew",
    "Sandslash",
    "Alolan Sandslash",
    "Nidoran♀",
    "Nidorina",
    "Nidoqueen",
    "Nidoran♂",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Alolan Vulpix",
    "Ninetales",
    "Alolan Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Alolan Diglett",
    "Dugtrio",
    "Alolan Dugtrio",
    "Meowth",
    "Alolan Meowth",
    "Alolan Meowth",
    "Persian",
    "Alolan Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Hisuian Growlithe",
    "Arcanine",
    "Hisuian Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Mega Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Alolan Geodude",
    "Graveler",
    "Alolan Graveler",
    "Golem",
    "Alolan Golem",
    "Ponyta",
    "Galarian Ponyta",
    "Rapidash",
    "Galarian Rapidash",
    "Slowpoke",
    "Galarian Slowpoke",
    "Slowbro",
    "Galarian Slowbro",
    "Galarian Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch’d",
    "Farfetch’d",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Alolan Grimer",
    "Muk",
    "Alolan Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Mega Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Hisuian Voltorb",
    "Electrode",
    "Hisuian Electrode",
    "Exeggcute",
    "Exeggutor",
    "Alolan Exeggutor",
    "Cubone",
    "Marowak",
    "Alolan Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Galarian Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Mega Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Mega Pinsir",
    "Tauros",
    "Tauros",
    "Tauros",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Mega Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Eevee-1",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Mega Aerodactyl",
    "Snorlax",
    "Articuno",
    "Galarian Articuno",
    "Zapdos",
    "Galarian Zapdos",
    "Moltres",
    "Galarian Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mega Mewtwo X",
    "Mega Mewtwo Y",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Hisuian Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Mega Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Paldean Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Galarian Slowking",
    "Misdreavus",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Mega Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Hisuian Qwilfish",
    "Scizor",
    "Mega Scizor",
    "Shuckle",
    "Heracross",
    "Mega Heracross",
    "Sneasel",
    "Hisuian Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Galarian Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Mega Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Mega Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Mega Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mega Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Mega Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Galarian Zigzagoon",
    "Linoone",
    "Galarian Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Mega Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mega Sableye",
    "Mawile",
    "Mega Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Mega Aggron",
    "Meditite",
    "Medicham",
    "Mega Medicham",
    "Electrike",
    "Manectric",
    "Mega Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Mega Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Mega Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Mega Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Castform",
    "Castform",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Mega Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Mega Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Mega Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Mega Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Mega Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Mega Latias",
    "Latios",
    "Mega Latios",
    "Kyogre",
    "Primal Kyogre",
    "Groudon",
    "Primal Groudon",
    "Rayquaza",
    "Mega Rayquaza",
    "Jirachi",
    "Deoxys",
    "Deoxys",
    "Deoxys",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Burmy",
    "Burmy",
    "Wormadam",
    "Wormadam",
    "Wormadam",
    "Mothim",
    "Mothim",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Cherrim",
    "Shellos",
    "Shellos",
    "Gastrodon",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mega Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Mega Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Mega Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Mega Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Mega Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Rotom",
    "Rotom",
    "Rotom",
    "Rotom",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Origin Dialga",
    "Palkia",
    "Origin Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Origin Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Shaymin",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Arceus",
    "Victini",
    "Snivy",
    "Servine",
    "Serperior",
    "Tepig",
    "Pignite",
    "Emboar",
    "Oshawott",
    "Dewott",
    "Samurott",
    "Hisuian Samurott",
    "Patrat",
    "Watchog",
    "Lillipup",
    "Herdier",
    "Stoutland",
    "Purrloin",
    "Liepard",
    "Pansage",
    "Simisage",
    "Pansear",
    "Simisear",
    "Panpour",
    "Simipour",
    "Munna",
    "Musharna",
    "Pidove",
    "Tranquill",
    "Unfezant",
    "Blitzle",
    "Zebstrika",
    "Roggenrola",
    "Boldore",
    "Gigalith",
    "Woobat",
    "Swoobat",
    "Drilbur",
    "Excadrill",
    "Audino",
    "Mega Audino",
    "Timburr",
    "Gurdurr",
    "Conkeldurr",
    "Tympole",
    "Palpitoad",
    "Seismitoad",
    "Throh",
    "Sawk",
    "Sewaddle",
    "Swadloon",
    "Leavanny",
    "Venipede",
    "Whirlipede",
    "Scolipede",
    "Cottonee",
    "Whimsicott",
    "Petilil",
    "Lilligant",
    "Hisuian Lilligant",
    "Basculin",
    "Basculin",
    "Basculin",
    "Sandile",
    "Krokorok",
    "Krookodile",
    "Darumaka",
    "Galarian Darumaka",
    "Darmanitan",
    "Galarian Darmanitan",
    "Galarian Darmanitan",
    "Galarian Darmanitan",
    "Maractus",
    "Dwebble",
    "Crustle",
    "Scraggy",
    "Scrafty",
    "Sigilyph",
    "Yamask",
    "Galarian Yamask",
    "Cofagrigus",
    "Tirtouga",
    "Carracosta",
    "Archen",
    "Archeops",
    "Trubbish",
    "Garbodor",
    "Zorua",
    "Hisuian Zorua",
    "Zoroark",
    "Hisuian Zoroark",
    "Minccino",
    "Cinccino",
    "Gothita",
    "Gothorita",
    "Gothitelle",
    "Solosis",
    "Duosion",
    "Reuniclus",
    "Ducklett",
    "Swanna",
    "Vanillite",
    "Vanillish",
    "Vanilluxe",
    "Deerling",
    "Deerling",
    "Deerling",
    "Deerling",
    "Sawsbuck",
    "Sawsbuck",
    "Sawsbuck",
    "Sawsbuck",
    "Emolga",
    "Karrablast",
    "Escavalier",
    "Foongus",
    "Amoonguss",
    "Frillish",
    "Jellicent",
    "Alomomola",
    "Joltik",
    "Galvantula",
    "Ferroseed",
    "Ferrothorn",
    "Klink",
    "Klang",
    "Klinklang",
    "Tynamo",
    "Eelektrik",
    "Eelektross",
    "Elgyem",
    "Beheeyem",
    "Litwick",
    "Lampent",
    "Chandelure",
    "Axew",
    "Fraxure",
    "Haxorus",
    "Cubchoo",
    "Beartic",
    "Cryogonal",
    "Shelmet",
    "Accelgor",
    "Stunfisk",
    "Galarian Stunfisk",
    "Mienfoo",
    "Mienshao",
    "Druddigon",
    "Golett",
    "Golurk",
    "Pawniard",
    "Bisharp",
    "Bouffalant",
    "Rufflet",
    "Braviary",
    "Hisuian Braviary",
    "Vullaby",
    "Mandibuzz",
    "Heatmor",
    "Durant",
    "Deino",
    "Zweilous",
    "Hydreigon",
    "Larvesta",
    "Volcarona",
    "Cobalion",
    "Terrakion",
    "Virizion",
    "Tornadus",
    "Tornadus-1",
    "Thundurus",
    "Thundurus-1",
    "Reshiram",
    "Zekrom",
    "Landorus",
    "Landorus-1",
    "Kyurem",
    "Kyurem-1",
    "Kyurem-2",
    "Keldeo",
    "Keldeo-1",
    "Meloetta",
    "Meloetta-1",
    "Genesect",
    "Genesect-1",
    "Genesect-2",
    "Genesect-3",
    "Genesect-4",
    "Chespin",
    "Quilladin",
    "Chesnaught",
    "Fennekin",
    "Braixen",
    "Delphox",
    "Froakie",
    "Frogadier",
    "Greninja",
    "Greninja-1",
    "Greninja-2",
    "Bunnelby",
    "Diggersby",
    "Fletchling",
    "Fletchinder",
    "Talonflame",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Scatterbug",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Spewpa",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Vivillon",
    "Litleo",
    "Pyroar",
    "Flabébé",
    "Flabébé",
    "Flabébé",
    "Flabébé",
    "Flabébé",
    "Floette",
    "Floette",
    "Floette",
    "Floette",
    "Floette",
    "Floette",
    "Florges",
    "Florges",
    "Florges",
    "Florges",
    "Florges",
    "Skiddo",
    "Gogoat",
    "Pancham",
    "Pangoro",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Furfrou",
    "Espurr",
    "Meowstic",
    "Meowstic",
    "Honedge",
    "Doublade",
    "Aegislash",
    "Aegislash",
    "Spritzee",
    "Aromatisse",
    "Swirlix",
    "Slurpuff",
    "Inkay",
    "Malamar",
    "Binacle",
    "Barbaracle",
    "Skrelp",
    "Dragalge",
    "Clauncher",
    "Clawitzer",
    "Helioptile",
    "Heliolisk",
    "Tyrunt",
    "Tyrantrum",
    "Amaura",
    "Aurorus",
    "Sylveon",
    "Hawlucha",
    "Dedenne",
    "Carbink",
    "Goomy",
    "Sliggoo",
    "Hisuian Sliggoo",
    "Goodra",
    "Hisuian Goodra",
    "Klefki",
    "Phantump",
    "Trevenant",
    "Pumpkaboo",
    "Pumpkaboo",
    "Pumpkaboo",
    "Pumpkaboo",
    "Gourgeist",
    "Gourgeist",
    "Gourgeist",
    "Gourgeist",
    "Bergmite",
    "Avalugg",
    "Hisuian Avalugg",
    "Noibat",
    "Noivern",
    "Xerneas",
    "Xerneas",
    "Yveltal",
    "Zygarde",
    "Zygarde",
    "Zygarde",
    "Zygarde",
    "Zygarde",
    "Diancie",
    "Mega Diancie",
    "Hoopa",
    "Hoopa",
    "Volcanion",
    "Rowlet",
    "Dartrix",
    "Decidueye",
    "Hisuian Decidueye",
    "Litten",
    "Torracat",
    "Incineroar",
    "Popplio",
    "Brionne",
    "Primarina",
    "Pikipek",
    "Trumbeak",
    "Toucannon",
    "Yungoos",
    "Gumshoos",
    "Grubbin",
    "Charjabug",
    "Vikavolt",
    "Crabrawler",
    "Crabominable",
    "Oricorio",
    "Oricorio",
    "Oricorio",
    "Oricorio",
    "Cutiefly",
    "Ribombee",
    "Rockruff",
    "Rockruff",
    "Lycanroc",
    "Lycanroc-1",
    "Lycanroc-2",
    "Wishiwashi",
    "Wishiwashi",
    "Mareanie",
    "Toxapex",
    "Mudbray",
    "Mudsdale",
    "Dewpider",
    "Araquanid",
    "Fomantis",
    "Lurantis",
    "Morelull",
    "Shiinotic",
    "Salandit",
    "Salazzle",
    "Stufful",
    "Bewear",
    "Bounsweet",
    "Steenee",
    "Tsareena",
    "Comfey",
    "Oranguru",
    "Passimian",
    "Wimpod",
    "Golisopod",
    "Sandygast",
    "Palossand",
    "Pyukumuku",
    "Type: Null",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Silvally",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Minior",
    "Komala",
    "Turtonator",
    "Togedemaru",
    "Mimikyu",
    "Mimikyu",
    "Bruxish",
    "Drampa",
    "Dhelmise",
    "Jangmo-o",
    "Hakamo-o",
    "Kommo-o",
    "Tapu Koko",
    "Tapu Lele",
    "Tapu Bulu",
    "Tapu Fini",
    "Cosmog",
    "Cosmoem",
    "Solgaleo",
    "Lunala",
    "Nihilego",
    "Buzzwole",
    "Pheromosa",
    "Xurkitree",
    "Celesteela",
    "Kartana",
    "Guzzlord",
    "Necrozma",
    "Necrozma",
    "Necrozma",
    "Necrozma",
    "Magearna",
    "Magearna",
    "Marshadow",
    "Poipole",
    "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Zeraora",
    "Meltan",
    "Melmetal",
    "Grookey",
    "Thwackey",
    "Rillaboom",
    "Scorbunny",
    "Raboot",
    "Cinderace",
    "Sobble",
    "Drizzile",
    "Inteleon",
    "Skwovet",
    "Greedent",
    "Rookidee",
    "Corvisquire",
    "Corviknight",
    "Blipbug",
    "Dottler",
    "Orbeetle",
    "Nickit",
    "Thievul",
    "Gossifleur",
    "Eldegoss",
    "Wooloo",
    "Dubwool",
    "Chewtle",
    "Drednaw",
    "Yamper",
    "Boltund",
    "Rolycoly",
    "Carkol",
    "Coalossal",
    "Applin",
    "Flapple",
    "Appletun",
    "Silicobra",
    "Sandaconda",
    "Cramorant",
    "Cramorant",
    "Cramorant",
    "Arrokuda",
    "Barraskewda",
    "Toxel",
    "Toxtricity",
    "Toxtricity-1",
    "Sizzlipede",
    "Centiskorch",
    "Clobbopus",
    "Grapploct",
    "Sinistea",
    "Sinistea-1",
    "Polteageist",
    "Polteageist-1",
    "Hatenna",
    "Hattrem",
    "Hatterene",
    "Impidimp",
    "Morgrem",
    "Grimmsnarl",
    "Obstagoon",
    "Perrserker",
    "Cursola",
    "Sirfetch'd",
    "Mr. Rime",
    "Runerigus",
    "Milcery",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Alcremie",
    "Falinks",
    "Pincurchin",
    "Snom",
    "Frosmoth",
    "Stonjourner",
    "Eiscue",
    "Eiscue-1",
    "Indeedee",
    "Indeedee",
    "Morpeko",
    "Morpeko-1",
    "Cufant",
    "Copperajah",
    "Dracozolt",
    "Arctozolt",
    "Dracovish",
    "Arctovish",
    "Duraludon",
    "Dreepy",
    "Drakloak",
    "Dragapult",
    "Zacian",
    "Zacian-1",
    "Zamazenta",
    "Zamazenta-1",
    "Eternatus",
    "Eternatus-1",
    "Kubfu",
    "Urshifu",
    "Urshifu-1",
    "Zarude",
    "Zarude-Dada",
    "Regieleki",
    "Regidrago",
    "Glastrier",
    "Spectrier",
    "Calyrex",
    "Calyrex-1",
    "Calyrex-2",
    "Wyrdeer",
    "Kleavor",
    "Ursaluna",
    "Bloodmoon Ursaluna",
    "Basculegion",
    "Basculegion",
    "Sneasler",
    "Overqwil",
    "Enamorus",
    "Enamorus-1",
    "Sprigatito",
    "Floragato",
    "Meowscarada",
    "Fuecoco",
    "Crocalor",
    "Skeledirge",
    "Quaxly",
    "Quaxwell",
    "Quaquaval",
    "Lechonk",
    "Oinkologne",
    "Oinkologne",
    "Dudunsparce",
    "Dudunsparce-1",
    "Tarountula",
    "Spidops",
    "Nymble",
    "Lokix",
    "Rellor",
    "Rabsca",
    "Greavard",
    "Houndstone",
    "Flittle",
    "Espathra",
    "Farigiraf",
    "Wiglett",
    "Wugtrio",
    "Dondozo",
    "Veluza",
    "Finizen",
    "Palafin",
    "Palafin",
    "Smoliv",
    "Dolliv",
    "Arboliva",
    "Capsakid",
    "Scovillain",
    "Tadbulb",
    "Bellibolt",
    "Varoom",
    "Revavroom",
    "Orthworm",
    "Tandemaus",
    "Maushold",
    "Maushold-1",
    "Cetoddle",
    "Cetitan",
    "Frigibax",
    "Arctibax",
    "Baxcalibur",
    "Tatsugiri",
    "Tatsugiri-1",
    "Tatsugiri-2",
    "Cyclizar",
    "Pawmi",
    "Pawmo",
    "Pawmot",
    "Wattrel",
    "Kilowattrel",
    "Bombirdier",
    "Squawkabilly",
    "Squawkabilly",
    "Squawkabilly",
    "Squawkabilly",
    "Flamigo",
    "Klawf",
    "Nacli",
    "Naclstack",
    "Garganacl",
    "Glimmet",
    "Glimmora",
    "Shroodle",
    "Grafaiai",
    "Fidough",
    "Dachsbun",
    "Maschiff",
    "Mabosstiff",
    "Bramblin",
    "Brambleghast",
    "Gimmighoul",
    "Gimmighoul",
    "Gholdengo",
    "Great Tusk",
    "Brute Bonnet",
    "Walking Wake",
    "Sandy Shocks",
    "Scream Tail",
    "Flutter Mane",
    "Slither Wing",
    "Roaring Moon",
    "Iron Treads",
    "Iron Leaves",
    "Iron Moth",
    "Iron Hands",
    "Iron Jugulis",
    "Iron Thorns",
    "Iron Bundle",
    "Iron Valiant",
    "Ting-Lu",
    "Chien-Pao",
    "Wo-Chien",
    "Chi-Yu",
    "Koraidon",
    "Koraidon",
    "Koraidon",
    "Koraidon",
    "Koraidon",
    "Miraidon",
    "Miraidon",
    "Miraidon",
    "Miraidon",
    "Miraidon",
    "Tinkatink",
    "Tinkatuff",
    "Tinkaton",
    "Charcadet",
    "Armarouge",
    "Ceruledge",
    "Toedscool",
    "Toedscruel",
    "Kingambit",
    "Clodsire",
    "Annihilape",
    "Ogerpon",
    "Ogerpon Wellspring",
    "Ogerpon Hearthflame",
    "Ogerpon Cornerstone",
    "Ogerpon-1",
    "Ogerpon Wellspring-1",
    "Ogerpon Hearthflame-1",
    "Ogerpon Cornerstone-1",
    "Dipplin",
    "Hydrapple",
    "Okidogi",
    "Munkidori",
    "Fezandipiti",
    "Gouging Fire",
    "Raging Bolt",
    "Iron Crown",
    "Iron Boulder",
    "Terapagos",
    "Terapagos-1",
    "Terapagos-2",
    "Pecharunt",
    "Archaludon",
    "Poltchageist",
    "Poltchageist-1",
    "Sinistcha",
    "Sinistcha-1",
)
