GEMTYPE = [
    "DEFAULT",
    "DRAGON",
    "HAGANE",
    "HIKOU",
    "JIMEN",
    "DENKI",
    "ESPER",
    "KOORI",
    "KUSA",
    "MIZU",
    "MUSHI",
    "NORMAL",
    "KAKUTOU",
    "HONOO",
    "GHOST",
    "AKU",
    "FAIRY",
    "IWA",
    "DOKU",
]

BALLIDS = [
    "MASUTAABOORU",
    "MONSUTAABOORU",
    "HAIPAABOORU",
    "TAIMAABOORU",
    "RIPIITOBOORU",
    "GOOZYASUBOORU",
    "KUIKKUBOORU",
    "HIIRUBOORU",
    "NESUTOBOORU",
    "HEBIIBOORU",
    "PUREMIABOORU",
]

STATS_COLUMNS = [
    "base_stats.HP",
    "base_stats.ATK",
    "base_stats.DEF",
    "base_stats.SPA",
    "base_stats.SPD",
    "base_stats.SPE",
]

INT_COLUMNS = [
    "type_1",
    "type_2",
    "ability_1",
    "ability_2",
    "ability_hidden",
    "xp_growth",
    "catch_rate",
    "egg_group_1",
    "egg_group_2",
    "egg_hatch_steps",
    "base_friendship",
    "evo_stage",
    "dex.index",
    "dex.group",
    "kitakami_dex",
    "exp_addend",
    "moneyRate",
]
